name: Premerge

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        vendor: [apple, pc-windows, unknown-linux]
        toolchain: [gnu, msvc, darwin]
        exclude:
          - runner: windows-latest
            arch: aarch64

          - runner: windows-latest
            vendor: apple

          - runner: windows-latest
            vendor: unknown-linux

          - runner: ubuntu-latest
            vendor: pc-windows

          - runner: ubuntu-latest
            vendor: apple

          - runner: ubuntu-24.04-arm
            vendor: pc-windows

          - runner: ubuntu-24.04-arm
            vendor: apple

          - runner: macos-latest
            vendor: pc-windows

          - runner: macos-latest
            vendor: unknown-linux

          - runner: ubuntu-latest
            arch: aarch64

          - runner: ubuntu-24.04-arm
            arch: x86_64

          - runner: macos-latest
            toolchain: gnu

          - runner: macos-latest
            toolchain: msvc

          - runner: ubuntu-latest
            toolchain: darwin

          - runner: ubuntu-latest
            toolchain: msvc

          - runner: ubuntu-24.04-arm
            toolchain: darwin

          - runner: ubuntu-24.04-arm
            toolchain: msvc

          - runner: windows-latest
            toolchain: darwin

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: rustup target add ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.toolchain }}

      - run: cargo build --target ${{ matrix.arch }}-${{ matrix.vendor }}-${{ matrix.toolchain }}
        env:
          RUSTFLAGS: '-D warnings'

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: cargo test
        env:
          RUSTFLAGS: '-D warnings'

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - uses: actions-rust-lang/rustfmt@v1
        env:
          RUSTFLAGS: '-D warnings'
